Daily_Comic/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('home.urls')),
    path('products/', include('products.urls')),
    path('bag/', include('bag.urls')),
    path('checkout/', include('checkout.urls')),
    path('profile/', include('profiles.urls')),
    path('contact/', include('contact.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bag/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.see_the_basket, name='see_the_basket'),
    path('add/<item_id>', views.add_to_basket, name='add_to_basket'),
    path('quickadd/<item_id>', views.quick_add, name='quick_add'),
    path('adjust/<item_id>/', views.adjust_basket, name='adjust_basket'),
    path(
        'remove/<item_id>/',
        views.remove_from_basket,
        name='remove_from_basket'),
]

products/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.all_stock, name='products'),
    path('<int:product_id>/', views.item_detail, name='item_detail'),
    path('addreview/', views.Add_Review, name='add_review'),
    path('addproduct/', views.add_a_product, name='add_a_product'),
    path(
        'edit/<int:product_id>/',
        views.edit_the_product,
        name='edit_the_product'),
    path(
        'delete/<int:product_id>/',
        views.delete_the_product,
        name='delete_the_product'),
    ]

checkout/models.py
import uuid

from django.db import models
from django.db.models import Sum
from django.conf import settings
from django_countries.fields import CountryField
from products.models import Product
from profiles.models import Userprofiles


class Order(models.Model):
    order_number = models.CharField(max_length=32, null=False, editable=False)
    user_profile = models.ForeignKey(
        Userprofiles, on_delete=models.SET_NULL, null=True,
        blank=True, related_name='orders')
    full_name = models.CharField(max_length=50, null=False, blank=False)
    email = models.EmailField(max_length=254, null=False, blank=False)
    phone_number = models.CharField(max_length=20, null=False, blank=False)
    country = CountryField(blank_label="Country *", null=False, blank=False)
    postcode = models.CharField(max_length=20, null=True, blank=True)
    town_or_city = models.CharField(max_length=40, null=False, blank=False)
    street_address1 = models.CharField(max_length=80, null=False, blank=False)
    street_address2 = models.CharField(max_length=80, null=True, blank=True)
    county = models.CharField(max_length=80, null=True, blank=True)
    date = models.DateTimeField(auto_now_add=True)
    delivery_cost = models.DecimalField(
        max_digits=6, decimal_places=2, null=False, default=0)
    order_total = models.DecimalField(
        max_digits=10, decimal_places=2, null=False, default=0)
    grand_total = models.DecimalField(
        max_digits=10, decimal_places=2, null=False, default=0)
    original_bag = models.TextField(null=False, blank=False, default='')
    stripe_pid = models.CharField(
        max_length=254, null=False, blank=False, default='')

    def _generate_order_number(self):
        """
        Create a unique order number using UUID
        """
        return uuid.uuid4().hex.upper()

    def update_total(self):
        """
        Update grand total each time a line item is added,
        accounting for delivery costs.
        """
        self.order_total = self.lineitems.aggregate(
            Sum('lineitem_total'))['lineitem_total__sum'] or 0
        if self.order_total < settings.FREE_DELIVERY_THRESHOLD:
            self.delivery_cost = (
                self.order_total * settings.STANDARD_DELIVERY_PERCENTAGE / 100)
        else:
            self.delivery_cost = 0
        self.grand_total = self.order_total + self.delivery_cost
        self.save()

    def save(self, *args, **kwargs):
        """
        Override the original save method to set the order number
        if it hasn't been set already.
        """
        if not self.order_number:
            self.order_number = self._generate_order_number()
        super().save(*args, **kwargs)

    def __str__(self):
        return self.order_number


class OrderLineItem(models.Model):
    order = models.ForeignKey(
        Order, null=False, blank=False, on_delete=models.CASCADE, related_name='lineitems')
    product = models.ForeignKey(
        Product, null=False, blank=False, on_delete=models.CASCADE)
    sub_id = models.CharField(max_length=254, blank=True)
    product_size = models.CharField(
        max_length=2, null=True, blank=True)  # XS, S, M, L, XL
    quantity = models.IntegerField(null=False, blank=False, default=0)
    lineitem_total = models.DecimalField(
        max_digits=6, decimal_places=2,
        null=False, blank=False, editable=False)

    def save(self, *args, **kwargs):
        """
        Override the original save method to set the lineitem total
        and update the order total.
        """
        self.lineitem_total = self.product.price * self.quantity
        super().save(*args, **kwargs)

    def __str__(self):
        return f'SKU {self.product.sku} on order {self.order.order_number}'

products/models.py
from django.db import models


class Category(models.Model):

    class Meta:
        verbose_name_plural = 'Categories'

    name = models.CharField(max_length=254)
    friendly_name = models.CharField(max_length=254, blank=True)

    def __str__(self):
        return self.name

    def get_friendly_name(self):
        return self.friendly_name


class Product(models.Model):
    category = models.ForeignKey(
        'Category', null=True, blank=True, on_delete=models.SET_NULL)
    sku = models.CharField(max_length=254, blank=True)
    name = models.CharField(max_length=254)
    universe = models.CharField(max_length=254, blank=True)
    hero = models.CharField(max_length=254, blank=True)
    author = models.CharField(max_length=254, blank=True)
    artist = models.CharField(max_length=254, blank=True)
    publishedby = models.CharField(max_length=254, blank=True)
    description = models.TextField()
    has_sizes = models.BooleanField(default=False, null=True, blank=True)
    rrp = models.DecimalField(max_digits=6, decimal_places=2)
    price = models.DecimalField(max_digits=6, decimal_places=2)
    image_url = models.URLField(
        max_length=1024, blank=True)
    image = models.ImageField(blank=True)

    def __str__(self):
        return self.name


class Reviews(models.Model):
    product = models.ForeignKey(
        'Product', null=True, blank=True, on_delete=models.SET_NULL)
    name = models.CharField(max_length=254)
    rating = models.IntegerField(blank=False)
    date = models.DateTimeField(auto_now_add=True)
    description = models.TextField()

    def __str__(self):
        return self.name

products/forms.py
from django import forms
from .models import Reviews, Product, Category


class ReviewForm(forms.ModelForm):

    rating = forms.IntegerField(min_value=0, max_value=5)

    class Meta:
        model = Reviews
        fields = ('product', 'name', 'rating', 'description')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'product-text'


class ProductForm(forms.ModelForm):

    class Meta:
        model = Product
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        categories = Category.objects.all()
        friendly_names = [(c.id, c.get_friendly_name()) for c in categories]

        self.fields['category'].choices = friendly_names
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'product-text'

products/views.py
from django.shortcuts import (
    render, get_object_or_404, redirect, reverse, HttpResponseRedirect)
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.db.models import Q, Avg
from .models import Product, Category, Reviews
from .forms import ReviewForm, ProductForm


def all_stock(request):
    """ A view to show all products """
    products = Product.objects.all()
    query = None
    categories = None
    sort = None
    direction = None
    queryset = None

    if request.GET:

        if 'qset' in request.GET:
            queryset = request.GET['qset']
            thequery = Q(
                universe__contains=queryset) | Q(hero__icontains=queryset)
            products = products.filter(thequery)
        if 'sort' in request.GET:
            sortkey = request.GET['sort']
            sort = sortkey

            if 'direction' in request.GET:
                direction = request.GET['direction']
                if direction == 'desc':
                    sortkey = f'-{sortkey}'
            products = products.order_by(sortkey)

        if 'category' in request.GET:
            categories = request.GET['category'].split(',')
            products = products.filter(category__name__in=categories)
            categories = Category.objects.filter(name__in=categories)

        if 'q' in request.GET:
            query = request.GET['q']
            if not query:
                messages.error(
                    request, "You didn't enter any search criteria!")
                return redirect(reverse('products'))

            queries = Q(
                name__icontains=query) | Q(description__icontains=query)
            products = products.filter(queries)

    current_sorting = f'{sort}_{direction}'

    context = {
        'products': products,
        'search_term': query,
        'current_categories': categories,
        'current_sorting': current_sorting,
    }

    return render(request, 'products/products.html', context)


def item_detail(request, product_id):
    """ A veiw to show individual items """
    product = get_object_or_404(Product, pk=product_id)
    reviews = Reviews.objects.filter(product=product_id)
    form = ReviewForm()
    average = reviews.aggregate(Avg('rating'))
    rating = average['rating__avg']
    sort = None
    direction = None

    if request.GET:
        if 'sort' in request.GET:
            sortkey = request.GET['sort']
            sort = sortkey

            if 'direction' in request.GET:
                direction = request.GET['direction']
                if direction == 'desc':
                    sortkey = f'-{sortkey}'
            reviews = reviews.order_by(sortkey)
    current_sorting = f'{sort}_{direction}'

    context = {
        'product': product,
        'reviews': reviews,
        'form': form,
        'average_rating': rating,
        'current_sorting': current_sorting,
    }

    return render(request, 'products/item-detail.html', context)


def Add_Review(request):
    """ Add a product to the store """

    if request.method == 'POST':

        form = ReviewForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(
                request, 'Successfully Added Your Review! Thank You!')
            return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


@login_required
def add_a_product(request):
    """ Add a product to the store """
    if not request.user.is_superuser:
        return redirect(reverse('home'))

    if request.method == 'POST':
        form = ProductForm(request.POST, request.FILES)
        if form.is_valid():
            product = form.save()
            messages.success(request, 'Successfully added product!')
            return redirect(reverse('item_detail', args=[product.id]))
    else:
        form = ProductForm()

    template = 'products/add_a_product.html'
    context = {
        'form': form,
    }

    return render(request, template, context)


@login_required
def edit_the_product(request, product_id):
    """ Edit a product in the store """
    if not request.user.is_superuser:
        return redirect(reverse('home'))

    product = get_object_or_404(Product, pk=product_id)
    if request.method == 'POST':
        form = ProductForm(request.POST, request.FILES, instance=product)
        if form.is_valid():
            form.save()
            return redirect(reverse('item_detail', args=[product.id]))
        else:
            messages.error(
                request,
                'Failed to add product. Please ensure the form is valid.')
    else:
        form = ProductForm(instance=product)
        messages.info(request, f'You are editing {product.name}')

    template = 'products/edit_the_product.html'
    context = {
        'form': form,
        'product': product,
    }

    return render(request, template, context)


@login_required
def delete_the_product(request, product_id):
    """ Delete a product from the store """
    if not request.user.is_superuser:
        return redirect(reverse('home'))

    product = get_object_or_404(Product, pk=product_id)
    product.delete()
    messages.warning(request, 'Product deleted!')
    return redirect(reverse('products'))

products/templates/products/add_a_product.html
{% extends 'base.html' %} 
{% load static %} 
{% block content %}

<div class="hero-image1">
  <div class="hero-text">
    <h1>Product Mangement</h1>
  </div>
</div>
<div class="container justify-content-md-center mt-4">
  <div class="card mb-4">
    <div class="card-header card-heading -6">
      Add a Product
    </div>
    <div class="card-body">
      <form
        method="POST"
        action="{% url 'add_a_product' %}"
        class="form mb-2"
        enctype="multipart/form-data"
      > 
        {% csrf_token %} 
        {{ form | crispy }}
        <div class="text-right">
          <button
            class="text-decoration-none btn-lg btn-warning produtPageButton"
            type="submit"
          >
            Add Product
          </button>
        </div>
      </form>
    </div>
  </div>
</div>

{% endblock %} 
{% block postloadjs %} 
{{ block.super }}
<script>
  $(document).ready(function () {
    $("label").addClass("product-title");
  });
</script>
{% endblock %}

products/templates/products/edit_the_product.html
{% extends 'base.html' %} {% load static %} {% block content %}

<div class="hero-image1">
  <div class="hero-text">
    <h1>Product Mangement</h1>
  </div>
</div>
<div class="container justify-content-md-center mt-4">
  <div class="card mb-4">
    <div class="card-header card-heading -6">
      Edit The Product
    </div>
    <div class="card-body">
      <form
        method="POST"
        action="{% url 'edit_the_product' product.id %}"
        class="form mb-2"
        enctype="multipart/form-data"
      >
        {% csrf_token %} 
        {{ form | crispy }}
        <div class="text-right">
          <button
            class="text-decoration-none btn-lg btn-warning produtPageButton"
            type="submit"
          >
            Edit Product
          </button>
        </div>
      </form>
    </div>
  </div>
</div>

{% endblock %} {% block postloadjs %} {{ block.super }}
<script>
  $(document).ready(function () {
    $("label").addClass("product-title");
  });
</script>
{% endblock %}

products/templates/products/item-detail.html
{% extends 'base.html' %} {% load static %} {% block content %}

<div class="hero-image1">
	<div class="hero-text">
		<h1>Product Details</h1>
	</div>
</div>
<div class="container">
	<div class="row justify-content-md-center">
   
		<div class="col-sm">
			<div class="image-container my-5">
				{% if product.image %}
				<a href="{{ product.image.url }}" target="_blank">
					<img
            class="img-thumbnail mx-auto d-block product-image"
            src="{{ product.image.url }}"
            alt="{{ product.name }}"
          />
        </a>
					{% else %}
					<a href="">
						<img
            class="img-fluid"
            src="{{ MEDIA_URL }}noimage.png"
            alt="{{ product.name }}"
          />
        </a>
						{% endif %}
			</div>
		</div>
		<div class="col-sm mb-5">
			<div id="accordion">
				<div class="card mt-4 mt-sm-none">
					<div class="card-header " id="headingOne">
						<h5 class="mb-0">
							<button
                class="btn btn-link text-decoration-none card-heading"
                data-toggle="collapse"
                data-target="#collapseOne"
                aria-expanded="true"
                aria-controls="collapseOne"
              >
                Item Overview
              </button>
						</h5>
					</div>

					<div id="collapseOne" class="collapse show" aria-labelledby="headingOne" data-parent="#accordion">
						<div class="card-body product-text text-center">
							<p class="mt-3 product-title">{{ product.name }}</p>
							{% if product.category %}
							<p class="small mt-1">
								<a class="text-muted" href="{% url 'products' %}?category={{ product.category.name }}">
									<i class="fas fa-tag mr-1"></i>{{ product.category.friendly_name }}
								</a>
							</p>
							{% endif %}
                          
							<small class=""
                ><i class="fas fa-star mr-1"></i>{{ average_rating }} / 5</small>
             
                
						 {% if product.universe %}
							<p class="mt-1">
								<strong> Universe: </strong> {{ product.universe }}
							</p>
							{% endif %} {% if product.author %}
							<p class="mt-1">
								<strong> Author: </strong> {{ product.author }}
							</p>
							{% endif %} {% if product.artist %}
							<p class="mt-1">
								<strong> Artist(s): </strong> {{ product.artist }}
							</p>
							{% endif %} {% if product.hero %}
							<p class="mt-1"><strong> Hero: </strong> {{ product.hero }}</p>
							{% endif %} {% if product.publishedby %}
							<p class="mt-1">
								<strong> Published By: </strong> {{ product.publishedby }}
							</p>

							{% endif %}
							<p class="lead mb-1 font-weight-bold text-danger">
								RRP: <del>{{ product.rrp }}</del>
							</p>
							<p class="lead mb-2 font-weight-bold">
								Our Price: £{{ product.price }}
							</p>
						</div>
					</div>
				</div>
				<div class="card">
					<div class="card-header" id="headingTwo">
						<h5 class="mb-0">
							<button
                class="btn btn-link collapsed text-decoration-none card-heading"
                data-toggle="collapse"
                data-target="#collapseTwo"
                aria-expanded="false"
                aria-controls="collapseTwo"
              >
                Item Description
              </button>
						</h5>
					</div>
					<div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordion">
						<div class="card-body">
							<p class="mt-3 product-text">{{ product.description }}</p>
						</div>
					</div>
				</div>
				{% if request.user.is_superuser %}
			
           <a href="{% url 'edit_the_product' product.id %}"><i class="fas fa-edit mr-1 text-warning"></i></a> | 
                                                  <a class="text-danger" href="{% url 'delete_the_product' product.id %}"><i class="fas fa-trash mr-1"></i></a>
                                                    
        
				{% endif %}
			</div>
			<form class="form" action="{% url 'add_to_basket' product.id %}" method="POST">
				{% csrf_token %}
				<div class="form-row">
					<div class="col-12">
						<p class="mt-3"><strong>Quantity:</strong></p>
						<div class="form-group w-50">
							<div class="input-group">
								<div class="input-group-prepend">
									<button
                    class="decrement-qty btn border-0 rounded-0 text-warning"
                    data-item_id="{{ product.id }}"
                    id="decrement-qty_{{ product.id }}"
                  >
                    <span class="icon">
                      <i class="fas fa-minus"></i>
                    </span>
                  </button>
								</div>
								<input
                  class="form-control qty_input"
                  type="number"
                  name="quantity"
                  value="1"
                  min="1"
                  max="99"
                  data-item_id="{{ product.id }}"
                  id="id_qty_{{ product.id }}"
                />
								<div class="input-group-append">
									<button
                    class="increment-qty btn border-0 rounded-0 text-warning"
                    data-item_id="{{ product.id }}"
                    id="increment-qty_{{ product.id }}"
                  >
                    <span class="icon">
                      <i class="fas fa-plus"></i>
                    </span>
                  </button>
								</div>
							</div>
						</div>
					</div>
					{% with product.has_sizes as s %} {% if s %}
					<div class="col-12">
						<p><strong>Size:</strong></p>
						<select
              class="form-control rounded-0 w-50"
              name="product_size"
              id="id_product_size"
            >
              <option value="xs">XS</option>
              <option value="s">S</option>
              <option value="m" selected>M</option>
              <option value="l">L</option>
              <option value="xl">XL</option>
            </select>
					</div>
					{% endif %} {% endwith %}
					<a href="{% url 'products' %}"
						class="text-decoration-none mt-2 btn btn-warning produtPageButton mb-3 mr-3">Continue
						shopping</a>
                         {% if product.is_subscription %}
                         {% if request.user.is_authenticated %}
                         	<input
            type="submit"
            class="mt-2 btn btn-warning produtPageButton mb-3"
            value="Add To Cart!"
          />
					<input type="hidden" id="checkout" name="redirect_url" value="{{ request.path }}" />
        </div>
        {% else %}
        <a href="{% url 'account_login' %}"
						class="text-decoration-none mt-2 btn btn-danger produtPageButton mb-3 mr-3">Please  Login/register to order this product</a>
    </div>
    {% endif %}
    {% else %}
                      
					<input
            type="submit"
            class="mt-2 btn btn-warning produtPageButton mb-3"
            value="Add To Cart!"
          />
					<input type="hidden" name="redirect_url" value="{{ request.path }}" />
        </div>  {% endif %}
			</form>
		</div>
	</div>
</div>

<div class="row">
	<div class="col-12">
		<h1 class="text-center">Customer Reviews</h1>
	</div>
	<div class="col-12">
		<div class="container">
			<div class="text-center">
				<button type="button" class="text-decoration-none mt-2 btn btn-warning produtPageButton mb-3 mr-3" data-toggle="modal" data-target="#exampleModal">
  Add a Review!
</button></div>

			<!-- Modal -->
			<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
				aria-hidden="true">
				<div class="modal-dialog" role="document">
					<div class="modal-content ">
						<div class="modal-header ">
							<h5 class="modal-title product-title " id="exampleModalLabel">Add Review</h5>
							<button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
						</div>
						<div class="modal-body">
							<form method="POST" action="{% url 'add_review' %}" class="form mb-2"
								enctype="multipart/form-data">
								{% csrf_token %}

								{{ form | crispy }}



								<div class="text-right">
									<a class="text-decoration-none  btn btn-danger produtPageButton"
										data-dismiss="modal">Cancel</a>
									<button class="text-decoration-none  btn btn-warning produtPageButton" type="submit">Add Review</button>
								</div>
							</form>
						</div>
					</div>
				</div>
			</div>

			{% if reviews %}
            <div class="sort-select-wrapper w-50">
				<select id="sort-selector" class="product-title custom-select-sm rounded-0 border border-{% if current_sorting != 'None_None' %}info{% else %}black{% endif %}">
                                <option value="reset" {% if current_sorting == 'None_None' %}selected{% endif %}>Sort by...</option>
                                <option value="date_asc" {% if current_sorting == 'date_asc' %}selected{% endif %}>Date (low to high)</option>
                                <option value="date_desc" {% if current_sorting == 'date_desc' %}selected{% endif %}>Date (high to low)</option>
                                <option value="rating_asc" {% if current_sorting == 'rating_asc' %}selected{% endif %}>Rating (low to high)</option>
                                <option value="rating_desc" {% if current_sorting == 'rating_desc' %}selected{% endif %}>Rating (high to low)</option>
                            </select>
			</div>
			{% for review in reviews %}

			<div class="card mb-3 reviews">
				<div class="card-header">
					<div class="row card-heading">
						<div class="col-6">
							<p class="mt-0 mb-1">
								<i class="far fa-hand-spock"></i> {{ review.name }}
							</p>
						</div>
						<div class="col-6 rating">
							<i class="fas fa-star"></i> {{ review.rating }}/5
						</div>
					</div>
				</div>
				<div class="card-body">
                <div class="row text-left">
                <div class="col-6">
					<p class="product-title">
						<i class="fas fa-comment-dots"></i> Description
					</p>
                </div>
                      <div class="col-6 rating product-title">
							<i class="fas fa-clock"></i> {{ review.date|date:"d M y" }}
						</div></div>
                         <div class="row pl-4">
					<p class="mb-3 product-text">{{ review.description }}</p>
				</div></div>
			</div>{% endfor %}

			{% else %}
			<p class="product-text text-center text-danger text-upper">No Reviews Added, Feel Free To Add Your Own</p>

			{% endif %}
		</div>
	</div>
</div>

{% endblock %}
{% block postloadjs %}
{{ block.super }}
{% include 'products/includes/quantity_input.html' %}
<script>
	$(document).ready(function(){
    $("select option[value={{ product.id }}]").attr('selected', 'selected');
    $("label").addClass("product-title");
})
$('#sort-selector').change(function() {
            var selector = $(this);
            var currentUrl = new URL(window.location);

            var selectedVal = selector.val();
            if(selectedVal != "reset"){
                var sort = selectedVal.split("_")[0];
                var direction = selectedVal.split("_")[1];

                currentUrl.searchParams.set("sort", sort);
                currentUrl.searchParams.set("direction", direction);

                window.location.replace(currentUrl);
            } else {
                currentUrl.searchParams.delete("sort");
                currentUrl.searchParams.delete("direction");

                window.location.replace(currentUrl);
            }
        })
</script>
{% endblock %}